server:
  port:  8083
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/pruebamsm?currentSchema=santamaria
    username: postgres
    password: bsarango
    driverClassName: org.postgresql.Driver